Lap5/Lap5/Controllers/CanHoController.cs
using Lap5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
namespace Lap5.Controllers
{
    public class CanHoController : Controller
    {
        public IActionResult ThemCanHo()
        {
            return View();
        }

        public IActionResult AddCH(CanHoModel canho)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            context.sqlInsertCanHo(canho);
            return new RedirectResult(url: "/CanHo/ThemCanHo", permanent: true, preserveMethod: true);
        }
    }
}

Lap5/Lap5/Controllers/NV_BTController.cs
using Microsoft.AspNetCore.Mvc;
using Lap5.Models;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
namespace Lap5.Controllers
{
    
    public class NV_BTController : Controller
    {
        public IActionResult LietKeLanSua()
        {
            return View();
        }

        public IActionResult ListNhanVienSoLanSua(int SoLan)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            return View(context.sqlListByTimeNhanVien(SoLan));
        }
        public IActionResult ViewLanSua(int MaNV, int MaTB, int MaCH, int LanThu, DateTime NgayBT)
        {
            NV_BTModel model = new NV_BTModel();
            model.MaNV = MaNV;
            model.MaTB = MaTB;
            model.MaCH = MaCH;
            model.LanThu = LanThu;
            model.NgayBT = NgayBT;
            return View(model);
        }
        public IActionResult UpdateSuaChua(int MaNV, int MaTBC, int MaCHC, int LanThuC, int MaTB, int MaCH, int LanThu, string NgayBT)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            context.sqlUpdateSuaChua(MaNV, MaTBC, MaCHC, LanThuC, MaTB, MaCH, LanThu, NgayBT);
            return new RedirectResult(url: "/NhanVien/ListNhanVienSua?MaNV=" + MaNV, permanent: true, preserveMethod: true);
        }
    }
}

Lap5/Lap5/Controllers/NhanVienController.cs
using Microsoft.AspNetCore.Mvc;
using Lap5.Models;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Collections;

namespace Lap5.Controllers
{
    public class NhanVienController : Controller
    {
        
        public IActionResult ListNhanVien()
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            return View(context.sqlListNhanVien());
        }

        public IActionResult ListNhanVienSua(int MaNV)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            return View(context.sqlLietKet(MaNV));
        }
        public IActionResult XoaLanSua(int MaNV, int MaTB, int MaCH, int LanThu)
        {
            DataContext context = HttpContext.RequestServices.GetService(typeof(Lap5.Models.DataContext)) as DataContext;
            context.sqlXoaLanSua(MaNV, MaTB, MaCH, LanThu);
            return new RedirectResult(url: "/NhanVien/ListNhanVienSua?MaNV=" + MaNV, permanent: true, preserveMethod: true);
        }
    }
    
}

Lap5/Lap5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lap5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lap5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CanHo" asp-action="ThemCanHo">1. Thêm Căn Hộ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NV_BT" asp-action="LietKeLanSua">2. Liệt Kê Lần Sửa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="ListNhanVien">3. Liệt Kê Nhân Viên</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lap5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>